fixtures:
  repositories:
    jenkins: https://github.com/jenkinsci/puppet-jenkins.git

  forge_modules:
    archive: "puppet/archive"
    apt:
      repo: "puppetlabs/apt"
      ref: '2.4.0'
    concat:  "puppetlabs/concat"
    java:    "puppetlabs/java"
    stdlib:  "puppetlabs/stdlib"
    #jenkins: "rtyler/jenkins"

  symlinks:
    icinga_build: "#{source_dir}"
