---
sudo: false
dist: trusty
language: ruby
cache: bundler
before_install:
  - rm -f Gemfile.lock
script:
  - 'bundle exec rake $CHECK'
matrix:
  include:
  - rvm: 2.4.3
    env: PUPPET_VERSION="~> 5.0" CHECK=test
  - rvm: 2.1.10
    env: PUPPET_VERSION="~> 4.0" CHECK=test
branches:
  only:
  - master
  - /^v\d/
notifications:
  email: false
#deploy:
#  provider: puppetforge
#  deploy:
#    branch: master
#  user: someuser
#  password:
#    secure: "somepasswordhash"
#  on:
#    tags: true
    # all_branches is required to use tags
#    all_branches: true
    # Only publish the build marked with "DEPLOY_TO_FORGE"
#    condition: "$DEPLOY_TO_FORGE = yes"
